#if defined _class_blocker_menu_included
 #endinput
#endif
#define _class_blocker_menu_included

#define PLUGIN_NAME "Class blocker"
#define MENU_SELECT_PLAYER "Select player"
#define MENU_SELECT_TEAMS "Select team"
#define MENU_SELECT_CLASS "Select class"
#define ITEM_LENGTH 128
#define ITEM_ALLIES "Allies"
#define ITEM_AXIS "Axis"
#define ITEM_WEAPON_USE_ALLIES "Weapon use Allies"
#define ITEM_WEAPON_USE_AXIS "Weapon use Axis"
#define PLAYER_NAME_LENGTH 32
